echo "this is timmnix (dec 2014)"

if [ -z "$2" ]
then
	echo "usage bash install.sh USER EMAIL"
	exit	
fi

echo creating dirs ...
mkdir -p $HOME/tmp/backup

echo creating config ...
if [ ! -f "$HOME/.vimrc" ]; then
	echo "      .vimrc"
	ln -sf $HOME/timmnix/dotvim  $HOME/.vimrc
fi
if [ ! -f "$HOME/.emacs" ]; then
	echo "      .emacs"
	ln -sf $HOME/timmnix/dotemacs  $HOME/.emacs
fi

echo  "configuring config for [$1] at [$2] ..."
git config user.name "$1"
git config user.email "$2"

echo  looking for installs ...
All="aspell
aspell-en
bash
clisp
compiz
emacs
emacs-goodies-el
enscript
erlang						
erlang-appmon					
erlang-asn1					
erlang-base					
erlang-common-test				
erlang-corba					
erlang-crypto					
erlang-debugger					
erlang-dev					
erlang-dialyzer					
erlang-diameter					
erlang-edoc					
erlang-eldap					
erlang-erl-docgen				
erlang-et					
erlang-eunit					
erlang-examples					
erlang-gs					
erlang-ic					
erlang-ic-java					
erlang-inets					
erlang-jinterface				
erlang-megaco					
erlang-mnesia					
erlang-mode					
erlang-observer					
erlang-odbc					
erlang-os-mon					
erlang-parsetools				
erlang-percept					
erlang-pman					
erlang-public-key				
erlang-reltool					
erlang-runtime-tools				
erlang-snmp					
erlang-src					
erlang-ssh					
erlang-ssl					
erlang-syntax-tools				
erlang-test-server				
erlang-toolbar					
erlang-tools					
erlang-tv					
erlang-typer					
erlang-webtool					
erlang-xmerl					
ftp
gawk
gimp
git
gnu-smalltalk
graphviz
grep
groff
gzip
html2text
htop
idle
ispell
imagemagick
latex-beamer
latex-xcolor
latex2html
less
lftp
lua-doc
lua5.1
luadoc
luakit
luarocks
make
nano
pandoc
python						
python-appindicator				
python-apt					
python-apt-common				
python-aptdaemon				
python-aptdaemon.gtk3widgets			
python-beautifulsoup				
python-bzrlib					
python-cairo					
python-chardet					
python-cheetah					
python-cherrypy3				
python-compizconfig				
python-configglue				
python-configobj				
python-crypto					
python-cssselect				
python-cssutils					
python-cups					
python-cupshelpers				
python-dateutil					
python-dbus					
python-dbus-dev					
python-debian					
python-debtagshw				
python-decorator				
python-defer					
python-dev					
python-dirspec					
python-distro-info				
python-dnspython				
python-docutils					
python-egenix-mxdatetime			
python-egenix-mxtools				
python-epydoc					
python-feedparser				
python-gconf					
python-gi					
python-gi-cairo					
python-glade2					
python-gnome2					
python-gnomekeyring				
python-gobject					
python-gobject-2				
python-gpgme					
python-gst0.10					
python-gtk2					
python-httplib2					
python-ibus					
python-imaging					
python-imaging-compat				
python-keyring					
python-launchpadlib				
python-lazr.restfulclient			
python-lazr.uri					
python-ldap					
python-libxml2					
python-logilab-astng				
python-logilab-common				
python-lxml					
python-mako					
python-markdown					
python-markupsafe				
python-matplotlib				
python-matplotlib-data				
python-mechanize				
python-minimal					
python-mysqldb					
python-netaddr					
python-netifaces				
python-nevow					
python-notify					
python-numpy					
python-oauth					
python-oauthlib					
python-oneconf					
python-opengl					
python-openssl					
python-pam					
python-paramiko					
python-pexpect					
python-pip					
python-piston-mini-client			
python-pkg-resources				
python-protobuf					
python-pycurl					
python-pydoctor					
python-pygments					
python-pyinotify				
python-pyorbit					
python-pyparsing				
python-qt4					
python-qt4-dbus					
python-renderpm					
python-reportlab				
python-reportlab-accel				
python-repoze.lru				
python-requests					
python-roman					
python-routes					
python-scipy					
python-scour					
python-serial					
python-setuptools				
python-simplegeneric				
python-simplejson				
python-sip					
python-six					
python-smbc					
python-subvertpy				
python-support					
python-tdb					
python-tk					
python-tornado					
python-twisted-bin				
python-twisted-core				
python-twisted-names				
python-twisted-web				
python-tz					
python-uniconvertor				
python-urllib3					
python-utidylib					
python-wadllib					
python-webob					
python-xapian					
python-xdg					
python-zeitgeist				
python-zmq					
python-zope.interface				
python2.7					
python2.7-dev					
python2.7-minimal				
ruby
screen
slime
sbcl
subversion
sudo
swi-prolog
tar
texlive-base
tex-gyre					
texlive						
texlive-base					
texlive-bibtex-extra				
texlive-binaries									
texlive-extra-utils				
texlive-font-utils				
texlive-fonts-extra				
texlive-fonts-extra-doc				
texlive-fonts-recommended			
texlive-fonts-recommended-doc			
texlive-generic-recommended			
texlive-latex-base				
texlive-latex-base-doc				
texlive-latex-extra				
texlive-latex-extra-doc				
texlive-latex-recommended			
texlive-latex-recommended-doc			
texlive-luatex					
texlive-math-extra				
texlive-pictures				
texlive-pictures-doc				
texlive-pstricks				
texlive-pstricks-doc				
texlive-science					
texlive-science-doc				
texlive-xetex					
texpower					
tidy
tree
unzip
vim
weka
wget
zip
slrn"

if 	dpkg -s slrn 2> /dev/null > /dev/null 
then 	echo skipping installs
else  	sudo apt-get -q install $All
fi


